### ISSUE TITLE
DB Setup

### ISSUE THREAD

**Issue by PetRacoon** [BogBel/telegram-bidthdays#2]
Create file **models.py** in project root and describe using sqlachemy next models:
```
User:
    td_id: sqlalchemy.types.Integer
    tg_username:  sqlalchemy.types.String
    bday: sqlalchemy.types.DateTime
```

```
Group:
    type: choice from ('group', 'direct')
    target: sqlalchemy.types.String
    tz: Choice from **pytz.all_timezones**
```

Look for https://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html#many-to-many as a result of this issue you should have 2 classes **User** and **Group** and **UserGroup** association table.
